config_version = "0"

exclude_patterns = [
  "**/*.test.ts",
  "fs_root/"
]

[[source]]
name = "default"
default = true

[smells.function_parameters]
threshold = 4

[smells.boolean_logic]
threshold = 8

[smells.function_complexity]
threshold = 10

[smells.nested_control_flow]
threshold = 3

[[plugin]]
name = "semgrep"
