name: Contributor Agreement
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  contributor_agreement:
    name: Contributor Agreement
    runs-on: ubuntu-latest
    steps:
      - name: Contributor Agreement
        if: |
          github.event_name == 'pull_request_target' ||
          (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'CLA')) ||
          (github.event_name == 'issue_comment' && github.event.comment.body == 'recheck')
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: .signatures/cla.json
          path-to-document: CONTRIBUTOR_AGREEMENT.md
          branch: cla-signatures
          allowlist: daniellacosse
