name: Pull Request Automations

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  add_size_label:
    name: Add Size Label
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - if: ${{ !github.event.pull_request.head.repo.fork }}
        name: Add Size Label
        uses: pascalgn/size-label-action@v0.5.5
        env:
          IGNORED: |
            assets
            deno.lock
        with:
          sizes: >
            {
              "0": "size: small",
              "512": "size: medium",
              "1024": "size: large"
            }
